//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.SINOStock.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class FormWork
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string ProductModel { get; set; }
        [DataMember]
        public int BoxPCSQty { get; set; }
        [DataMember]
        public int BoxQty { get; set; }
        [DataMember]
        public int IDNumber { get; set; }
        [DataMember]
        public string IDKeyWords { get; set; }
        [DataMember]
        public int QieShu { get; set; }
        [DataMember]
        public int RowQty { get; set; }
        [DataMember]
        public int ColumnQty { get; set; }
        [DataMember]
        public System.DateTime CreateDt { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifyDt { get; set; }
    }
}
