//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.SINOStock.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Function
    {
        public Function()
        {
            this.FunctionDetails = new HashSet<FunctionDetail>();
            this.RuleMapFunctions = new HashSet<RuleMapFunction>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string FunctionName { get; set; }
    
        [DataMember]
        public virtual ICollection<FunctionDetail> FunctionDetails { get; set; }
        [DataMember]
        public virtual ICollection<RuleMapFunction> RuleMapFunctions { get; set; }
    }
}
