//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.SINOStock.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class StockLot
    {
        public StockLot()
        {
            this.StockDetails = new HashSet<StockDetail>();
        }
    
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public int PCSQty { get; set; }
        [DataMember]
        public string ProModel { get; set; }
        [DataMember]
        public string LotNo { get; set; }
        [DataMember]
        public System.DateTime CreateDt { get; set; }
        [DataMember]
        public int Status { get; set; }
        [DataMember]
        public bool IsJianBao { get; set; }
        [DataMember]
        public bool IsDuMo { get; set; }
        [DataMember]
        public string DetailInfoHOLD { get; set; }
        [DataMember]
        public string ImageHOLD { get; set; }
        [DataMember]
        public bool IsImport { get; set; }
        [DataMember]
        public int TuiHuoCount { get; set; }
        [DataMember]
        public string GuanKong { get; set; }
        [DataMember]
        public Nullable<int> CreateAccountID { get; set; }
        [DataMember]
        public string CreateAccountName { get; set; }
    
        [DataMember]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
    }
}
